language: node_js
node_js:
  - 8
cache:
  directories:
    - "node_modules"
script:
  - yarn deploy
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_USERNAME
  api_key: $NPM_TOKEN
  on:
    branch: master